[tool.poetry]
name = "rp2040-pio-emulator"
version = "0.25.0"
description = "RP2040 emulator for the testing and debugging of PIO programs"
authors = ["Nathan Young"]
license = "Apache-2.0"
repository = "https://github.com/NathanY3G/rp2040-pio-emulator"
readme = "README.md"
packages = [
    { include = "pioemu" }
]
keywords = [
    "rp2040",
    "raspberry-pi-pico",
    "testing",
    "tdd",
    "debugging",
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pylint = "^2.7.2"
pytest = "^6.2.2"
coverage = "^5.5"
black = "^21.5b0"
jupyter = "^1.0.0"
matplotlib = "^3.3.4"
seaborn = "^0.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
